config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  root 'homes#top'
  resources :books

 get 'home/about' => 'homes#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: { minimum:2, maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  # attachment
  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource_or_scope)
  	user_path(current_user.id)
  end

  def after_sign_out_path_for(resource_or_scope)
  	root_path
  end

protected
  def configure_permitted_parameters
 	devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
	def index
		@nbook = Book.new
		@books = Book.all.reverse_order
		@user = current_user
	end

	def create
		@nbook = Book.new(book_params)
		@nbook.user_id = current_user.id
		if @nbook.save
			flash[:notice] = "You have creatad book successfully."
			redirect_to book_path(@nbook.id)
		else
			@books = Book.all.reverse_order
			@user = current_user
			render action: :index
		end
	end

	def show
		@nbook = Book.new
		@book = Book.find(params[:id])
		@user = current_user
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user != current_user
			redirect_to books_path
		end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			flash[:notice] = "You have updated book successfully."
			redirect_to book_path(@book.id)
		else
			render action: :edit
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	private
	def book_params
		params.require(:book).permit(:title,:body)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def index
		@users = User.all
		@user = current_user
		@nbook = Book.new

	end
	def show
		@user = User.find(params[:id])
		@books = @user.books.reverse_order
		@nbook = Book.new
	end

	def edit
		@user = User.find(params[:id])
		if @user != current_user
			redirect_to user_path(current_user)
		end
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		    flash[:notice] = "You have updated user successfully."
		    redirect_to user_path(@user.id)
		else
			render action: :edit
	    end
	end

	private
	def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-xs-3">
  <h2>User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format:'jpeg', fallback:"no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
      <%= link_to edit_user_path(@user.id) do %>
       <div class="btn btn-default col-md-12"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></div>
      <% end %>
    </div>

  <h2>New book</h2>
  <div class="new-book-form">
  <%= form_for(@nbook) do |f| %>
  	<div class="row form-group">
  		<%= f.label :title, "title" %>
  		<%= f.text_field :title, class:"form-control" %>
  	</div>
  	<div class="row form-group">
  		<%= f.label :body, "opinion" %>
  		<%= f.text_area :body, class:"form-control" %>
  	</div>
  	<div class="row form-group">
  		<%= f.submit 'Create Book', class:"form-control btn btn-primary" %>
  	</div>
  <% end %>
  </div>
</div>

app/views/books/edit.html.erb
		<div class="col-xs-6 col-xs-offset-3">
			<!-- error-message -->
		    <% if @book.errors.any? %>
            <div class="error-explanation">
        	  <h2><%= @book.errors.count %> error prohibited this obj from being saved:</h2>
        	  <% @book.errors.full_messages.each do |message| %>
        	    <p><%= message %></p>
        	  <% end %>
            </div>
            <% end %>

			<h2>Editing Book</h2>
			<div class="edit-book-form">
			<%= form_for(@book) do |f| %>
			  <div class="row form-group">
			    <%= f.label :title, "Title" %>
				<%= f.text_field :title, class:"form-control" %>
			  </div>
			  <div class="row form-group">
			    <%= f.label :body, "Body" %>
			    <%= f.text_area :body, class:"form-control" %>
			  </div>
			  <div class="row form-group">
				<%= f.submit "Update Book", class:"form-control btn btn-primary" %>
			  </div>
			<% end %>
			</div>
			<%= link_to 'Show', book_path(@book.id) %>|<%= link_to 'Back', books_path %>
		</div>

app/views/books/index.html.erb

	<!-- error-message -->
	  <% if @nbook.errors.any? %>
	  <div class="error_explanation">
	    <h2><%= @nbook.errors.count %> errors prohibited this obj from being saved:</h2>
	    <ul>
	    <% @nbook.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
	    <% end %>
	    </ul>
	  </div>
	  <% end %>

      <!-- サイドバーを呼び出し -->
<div class="col-xs-3">
  <h2>User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format:'jpeg', fallback:"no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
      <%= link_to edit_user_path(@user.id) do %>
       <div class="btn btn-default col-md-12"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></div>
      <% end %>
    </div>

  <h2>New book</h2>
  <div class="new-book-form">
  <%= form_for(@nbook) do |f| %>
  	<div class="row form-group">
  		<%= f.label :title, "title" %>
  		<%= f.text_field :title, class:"form-control" %>
  	</div>
  	<div class="row form-group">
  		<%= f.label :body, "opinion" %>
  		<%= f.text_area :body, class:"form-control" %>
  	</div>
  	<div class="row form-group">
  		<%= f.submit 'Create Book', class:"form-control btn btn-primary" %>
  	</div>
  <% end %>
  </div>
</div>

        <div class="col-xs-9">
			<h2>Books</h2>
              <table class="table">
              	<thead>
	              <tr>
	              	<th>User</th>
	              	<th>Title</th>
	              	<th>Opinion</th>
	              </tr>
	            </thead>
              	<tbody>
              	<% @books.each do |book| %>
	              <tr>
	              	<td>
                        <%= link_to user_path(book.user) do %>
	              		  <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format:'jpeg', fallback:'no_image.jpg', size: '50x50' %>
	              		  </br><%= book.user.name %>
	              		<% end %>
	              	</td>
	              	<td>
	              		<%= link_to book_path(book.id) do %>
	              		  <%= book.title %>
	              		<% end %>
	              	</td>
	              	<td><%= book.body %></td>
	              </tr>
	            <% end %>
	            </tbody>
              </table>
		</div>



app/views/books/show.html.erb
	  <!-- success-massage -->
	  <% if flash[:notice] %>
	    <p><%= flash[:notice] %></p>
	  <% end %>

      <!-- サイドバーを呼び出し -->
      <div class="col-xs-3">
  <h2>User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format:'jpeg', fallback:"no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
      <%= link_to edit_user_path(@user.id) do %>
       <div class="btn btn-default col-md-12"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></div>
      <% end %>
    </div>

  <h2>New book</h2>
  <div class="new-book-form">
  <%= form_for(@nbook) do |f| %>
  	<div class="row form-group">
  		<%= f.label :title, "title" %>
  		<%= f.text_field :title, class:"form-control" %>
  	</div>
  	<div class="row form-group">
  		<%= f.label :body, "opinion" %>
  		<%= f.text_area :body, class:"form-control" %>
  	</div>
  	<div class="row form-group">
  		<%= f.submit 'Create Book', class:"form-control btn btn-primary" %>
  	</div>
  <% end %>
  </div>
</div>


      <div class="col-xs-9">
        <h2>Book detail</h2>
        <table class="table">
	      <tbody>
		    <tr>
		      <td>
		      	<%= link_to user_path(@book.user) do %>
		      	  <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format:'jpeg', fallback:'no_image.jpeg' %>
		      	  </br><%= @book.user.name %>
		      	<% end %>
		      </td>
		      <td><%= @book.title %></td>
		      <td><%= @book.body %></td>
		      <% if @book.user == current_user %>
		      <td>
		      	<%= link_to 'Edit', edit_book_path(@book), class:"btn btn-success" %>
		      </td>
		      <td>
		       <%= link_to 'Destroy', book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %>
		      </td>
		      <% end %>
		    </tr>
	      </tbody>
        </table>
      </div>


app/views/homes/about.html.erb
		<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>!</h1>

app/views/homes/top.html.erb
		<p class="notice"><%= notice %></p>
		<div class="col-lg-6 col-lg-offset-3">
			<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about various book!</p>
			<div class="row">
				<p class="btn btn-info col-md-10 col-md-offset-1">
					<%= link_to 'Log in', new_user_session_path %>
				</p>
			</div>
			<div class="row">
				<p class="btn btn-success col-md-10 col-md-offset-1">
					<%= link_to 'Sign Up', new_user_registration_path %>
				</p>
			</div>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersLevel2</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar bavbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span class="header-title">Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <%= link_to 'Home', user_path(current_user.id), class:"glyphicon glyphicon-home" %>
            </li>
            <li>
              <%= link_to 'Users', users_path, class:"glyphicon glyphicon-user" %>
            </li>
            <li>
              <%= link_to 'Books', books_path, class:"glyphicon glyphicon-book" %>
            </li>
            <li>
              <%= link_to 'logout', destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-out" %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Home', root_path, class:"glyphicon glyphicon-home" %>
            </li>
            <li>
              <%= link_to 'About', home_about_path, class:"glyphicon glyphicon-link" %>
            </li>
            <li>
              <%= link_to 'Sign up', new_user_registration_path, class:"glyphicon glyphicon-edit" %>
            </li>
            <li>
              <%= link_to 'login', new_user_session_path, class:"glyphicon glyphicon-log-in" %>
            </li>
          <% end %>
          </ul>
        </nav>
      </div>
    </header>

      <div class="container">
        <div class="row">
            <%= yield %>
        </div>
      </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-lg-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
	<!-- error-message -->
	<% if @user.errors.any? %>
	<div class="error_explanation">
		<h2><%= @user.errors.count %> errors prohibited this obj from being saved:</h2>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
			  <li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

    <!-- body -->
	<h2>User info</h2>
	<%= form_for(@user) do |f| %>
	<div>
	  <%= f.label :name, 'Name' %>
	  <%= f.text_field :name %>
	</div>
	<div>
	  <%= f.label :image, 'Image' %>
	  <%= f.attachment_field :profile_image %>
	</div>
	<div>
	  <%= f.label :introduction, 'Introduction' %>
	  <%= f.text_area :introduction %>
	</div>
	<div>
	  <%= f.submit 'Update User' %>
	</div>
	<% end %>

app/views/users/index.html.erb
		<%= render 'books/list' %>
		<div class="col-xs-9">
			<h2>Users</h2>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th>show</th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, format:'jpeg', fallback:'no_image.jpg', size: '50x50' %></td>
						<td><%= user.name %></td>
						<td><%= link_to 'Show', user_path(user.id) %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>

app/views/users/show.html.erb
		<!-- success-message -->
		<% if flash[:notice] %>
		  <p><%= flash[:notice] %></p>
		<% end %>

		<!-- sidebar -->
		<%= render 'books/list' %>

		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table">
				<thead>
					<tr>
						<th>User</th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
						  <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format:'jpeg', fallback:'no_image.jpeg' %>
						</td>
						<td>
						  <%= link_to book_path(book.id) do %>
							<%= book.title %>
						  <% end %>
						</td>
						<td><%= book.body %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>